---
- hosts: all
  gather_facts: true
  vars_files:
    - vars/jboss-eap.yml
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.jcliff
  roles:
    - jb_httpd
    - jcliff
    - eap
  pre_tasks:
    - include_tasks: tasks/prep.yml
  tasks:
    - name: "Fix JCliff standard-sockets rule"
      template:
        src: templates/standard-sockets
        dest: /usr/share/jcliff/rules/standard-sockets

    - name: "Force app redeploy"
      file:
        path: "{{ app_path }}"
        state: absent
      when:
        - app_redeploy is defined

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app_path }}"

    - include_tasks: tasks/jcliff.yml
      vars:
        management_port: "{{ 9990 + eap_port_range_shift }}"
        app:
          name: "{{ app_name }}-{{ app_version }}.war"
          path: "{{ app_path }}"

  post_tasks:
    - include_tasks: roles/eap/tasks/restart_eap.yml
      when:
        - upgrade_eap_software_id is defined

    - include_tasks: tasks/test.yml
      loop:
        - { url: 'http://localhost:8080/info/', port: 8080, result: /tmp/jboss.txt }
        - { url: 'http://localhost/info/', port: 80, result: /tmp/httpd.txt }

  handlers:
    - name: "JCliff"
      include_tasks: tasks/jcliff.yml
      vars:
        management_port: "{{ 9990 + eap_port_range_shift }}"
        app:
          name: "{{ app_name }}-{{ app_version }}.war"
          path: "{{ app_path }}"
