---
- hosts: all
  gather_facts: true
  vars:
    app_repository: /opt/apps
    app_name: info
    app_version: 1.0
    app_filename: "{{ app_name }}-{{ app_version }}.war"
    app_url: "http://people.redhat.com/~rpelisse/{{ app_filename }}"
    app_path: "{{ app_repository }}/{{ app_filename }}"

    # if gather_facts is set to true, the following variables can be removed
#    ansible_distribution: RedHat
#    ansible_os_family: RedHat
#    ansible_pkg_mgr: yum
#    ansible_distribution_version: 7.9
    #####

    jboss_user: jboss
    jboss_group: jboss
    jboss_install_dir: "{{ jboss_home | dirname }}"
    eap_software_id: "{{ upgrade_eap_software_id | default('64311') }}"
    eap_zipfile: "{{ app_repository }}/eap-{{ eap_software_id }}.zip"
    eap_instance_name: "{{ override_eap_instance_name | default('jboss-eap') }}"
    # To deploy 7.3 instead of 7.2: -e upgrade_eap_software_id=80101
    rhn_eap_download_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId={{ eap_software_id }}"
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.jcliff
  roles:
    - redhat_csp_download
    - jb_httpd
    - eap
    - jcliff
  pre_tasks:
    - assert:
        that:
          - ansible_distribution is defined
          - ansible_distribution == "RedHat"

    - set_fact:
         eap_port_range_shift: 0
         eap_version: 7.2
      when:
        - upgrade_eap_software_id is not defined

    - set_fact:
         eap_port_range_shift: 100
         eap_version: 7.3
      when:
        - upgrade_eap_software_id is defined

    - set_fact:
         jboss_home: "/opt/jboss-eap-{{ eap_version }}"
         eap_instance_name: "jboss-eap-{{ eap_version }}"

    - name: "Ensure JBOSS installation directory exists: {{ jboss_install_dir }}"
      file:
         path: "{{ jboss_install_dir }}"
         state: directory

    - debug:
        msg: "version: {{ ansible_distribution_version }}"

    - set_fact:
        rhel_version_specific_packages:
          - python-lxml
          - python-requests
      when:
        - ansible_distribution_version is defined
        - ansible_distribution_version is version('7.9','>=')

    - set_fact:
        rhel_version_specific_packages:
        - python3-lxml
      when:
        - ansible_distribution_version is defined
        - ansible_distribution_version is version('8.4','>=')

    - include_tasks: tasks/fastpackage.yml
      vars:
        package_name: "{{ item }}"
      loop:
        - unzip
        - zip
        - java-1.8.0-openjdk
        - mailcap

    - include_tasks: tasks/fastpackage.yml
      vars:
        package_name: "{{ item }}"
      loop: "{{ rhel_version_specific_packages }}"

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app_path }}"
      notify:
        - "JCliff"
  tasks:

  handlers:
    - name: "JCliff"
      include_tasks: tasks/jcliff.yml
      vars:
        management_port: "{{ 9990 + eap_port_range_shift }}"
        app:
          name: "{{ app_name }}-{{ app_version }}.war"
          path: "{{ app_path }}"
