---
- hosts: all
  gather_facts: false
  vars:
    app_repository: /opt/apps
    app_name: simple-webapp
    app_filename: "{{ app_name }}.war"
    app_url: "http://people.redhat.com/~rpelisse/{{ app_filename }}"
    app_path: "{{ app_repository }}/{{ app_filename }}"

    # if gather_facts is set to true, the following variables can be removed
    ansible_distribution: RedHat
    ansible_os_family: RedHat
    ansible_pkg_mgr: yum
    ansible_distribution_version: 7.9
    #####

    jboss_user: jboss
    jboss_group: jboss
    jboss_install_dir: "{{ jboss_home | dirname }}"
    eap_software_id: "{{ upgrade_eap_software_id | default('64311') }}"
    eap_zipfile: "{{ app_repository }}/eap-{{ eap_software_id }}.zip"
    eap_instance_name: "{{ override_eap_instance_name | default('jboss-eap') }}"
    # To deploy 7.3 instead of 7.2: -e upgrade_eap_software_id=80101
    rhn_eap_download_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId={{ eap_software_id }}"
  collections:
    - wildfly.jcliff
  roles:
    - sabre1041.redhat-csp-download
    - jb_httpd
    - jcliff
  tasks:
    - assert:
        that:
          - ansible_distribution is defined
          - ansible_distribution == "RedHat"

    - set_fact:
         eap_port_range_shift: 0
         eap_version: 7.2
      when:
        - upgrade_eap_software_id is not defined

    - set_fact:
         eap_port_range_shift: 100
         eap_version: 7.3
      when:
        - upgrade_eap_software_id is defined

    - set_fact:
         jboss_home: "/opt/jboss-eap-{{ eap_version }}"
         eap_instance_name: "jboss-eap-{{ eap_version }}"

    - name: "Ensure JBOSS installation directory exists: {{ jboss_install_dir }}"
      file:
         path: "{{ jboss_install_dir }}"
         state: directory

    - debug:
        msg: "version: {{ ansible_distribution_version }}"

    - set_fact:
        rhel_version_specific_packages:
          - python-lxml
          - python-requests
      when:
        - ansible_distribution_version is defined
        - ansible_distribution_version is version('7.9','>=')

    - set_fact:
        rhel_version_specific_packages:
        - python3-lxml
      when:
        - ansible_distribution_version is defined
        - ansible_distribution_version is version('8.4','>=')

    - include_tasks: tasks/fastpackage.yml
      vars:
        package_name: "{{ item }}"
      loop:
        - unzip
        - zip
        - java-1.8.0-openjdk

    - include_tasks: tasks/fastpackage.yml
      vars:
        package_name: "{{ item }}"
      loop: "{{ rhel_version_specific_packages }}"

    - group:
        name: "{{ jboss_group }}"
        state: present

    - user:
        name: "{{ jboss_user }}"
        state: present

    - assert:
        that:
          - rhn_username is defined
          - rhn_password is defined
          - jboss_home is defined
          - jboss_home | length > 0
        quiet: true

    - file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ jboss_install_dir }}"
        - "{{ app_repository }}"

    - name: "Install EAP with zipfile from RHN into JBOSS_HOME {{ jboss_home }}"
      redhat_csp_download:
        url: "{{ rhn_eap_download_url }}"
        dest: "{{  eap_zipfile }}"
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
      no_log: "{{ log_rhn_output | default('yes') }}"

    - stat:
        path: "{{ jboss_home }}"
      register: path_to_jboss_home

    - unarchive:
        src: "{{ eap_zipfile }}"
        dest: "{{ jboss_install_dir }}"
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
      when:
        - path_to_jboss_home is defined
        - path_to_jboss_home.stat is defined
        - not path_to_jboss_home.stat.exists

    - include_tasks: tasks/set-up-wildfy-service.yml
      vars:
        wildfly:
          home: "{{ jboss_home }}"
          user: "{{ jboss_user }}"
          group: "{{ jboss_group }}"
          pidfile: "{{ jboss_home }}/jboss.pid"
          port_range_offset: "{{ eap_port_range_shift }}"
          instance_name: "{{ eap_instance_name }}"
          config:
            name: garanti.xml
            base: standalone.xml

    - name: "Download a demo app to deploy"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app_path }}"

    - jcliff:
        wfly_home: "{{ jboss_home }}"
        management_port: "{{ 9990 + eap_port_range_shift }}"
        timeout: 7000
        subsystems:
          - system_properties:
              - name: JBOSS_EAP_HOME_FOLDER
                value: "{{ jboss_home | basename }}"
          - deployments:
              - name: "{{ app_name }}"
                path: "{{ app_path }}"
          - datasources:
              - name: ExampleDS2
                use_java_context: 'true'
                jndi_name: java:jboss/datasources/ExampleDS2
                connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
                driver_name: h2

  handlers:
    - name: "Reload Wildfly"
      command: "{{ jboss_home }}/bin/jboss-cli.sh --connect --command=':reload'"

    - name: "Restart Systemd Service"
      service:
         name: "{{ eap_instance_name }}"
         state: restarted
