---
- assert:
    that:
      - rhn_username is defined
      - rhn_password is defined
      - jboss_home is defined
      - jboss_home | length > 0
    quiet: true

- file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ jboss_install_dir }}"
    - "{{ app_repository }}"

- stat:
    path: "{{ jboss_home }}/bin/standalone.sh"
  register: is_jboss_already_installed

- name: "Install EAP with zipfile from RHN into JBOSS_HOME {{ jboss_home }}"
  redhat_csp_download:
    url: "{{ rhn_eap_download_url }}"
    dest: "{{  eap_zipfile }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  no_log: "{{ log_rhn_output | default('yes') }}"
  when:
    - is_jboss_already_installed is defined
    - is_jboss_already_installed.stat is defined
    - not is_jboss_already_installed.stat.exists

- stat:
    path: "{{ jboss_home }}"
  register: path_to_jboss_home

- unarchive:
    src: "{{ eap_zipfile }}"
    dest: "{{ jboss_install_dir }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
  when:
    - path_to_jboss_home is defined
    - path_to_jboss_home.stat is defined
    - not path_to_jboss_home.stat.exists
