---
- include_tasks: tasks/user_group.yml

- include_tasks: tasks/install_eap_from_rhn_zipfile.yml

- include_role:
    name: wildfly_systemd
  vars:
    wildfly: "wildfly"
    wildfly_home: "{{ jboss_home }}"
    wildfly_user: "{{ jboss_user }}"
    wildfly_group: "{{ jboss_group }}"
    wildfly_config_base: standalone-ha.xml
    #    wildfly_basedir_prefix: "{{ wildfly.basedir_prefix }}"
    wildfly_config_name: eap.xml
    instance_name: eap
