---
- include_tasks: tasks/user_group.yml

- include_tasks: tasks/install_eap_from_rhn_zipfile.yml

- include_tasks: tasks/set-up-wildfy-service.yml
  vars:
    wildfly:
      home: "{{ jboss_home }}"
      user: "{{ jboss_user }}"
      group: "{{ jboss_group }}"
      pidfile: "{{ jboss_home }}/jboss.pid"
      port_range_offset: "{{ eap_port_range_shift }}"
      instance_name: "{{ eap_instance_name }}"
      config:
        name: eap.xml
        base: standalone-ha.xml
