---
- name: "Reload Wildfly"
  include_tasks: tasks/reload.yml

- name: "Restart Systemd Service"
  include_tasks: tasks/restart_eap.yml

- name: "Activate modcluster"
  include_tasks: tasks/modcluster.yml
